# Jekyll設定
title: "Test Book"
description: "Testing Jekyll on GitHub Pages"
baseurl: "/test-book-20250710-01"
url: "https://ootakazuhiko.github.io"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown