# Jekyll設定
title: "AI時代に差がつく論理的思考と表現力"
description: "AI時代に必要な論理的思考力と効果的な表現力を身につけるための実践ガイド"
baseurl: "/test-book-20250710-01"
url: "https://ootakazuhiko.github.io"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed

# Build settings
markdown: kramdown

# Repository settings
repository:
  github: "https://github.com/ootakazuhiko/test-book-20250710-01"